---
build:
  stage: build
  image:
    name: quay.io/containers/buildah:latest
  variables:
    STORAGE_DRIVER: vfs
    BUILDAH_FORMAT: docker
    BUILDAH_ISOLATION: chroot
    FQ_IMAGE_NAME: $CI_REGISTRY_IMAGE/$CI_PROJECT_NAME:latest
  before_script:
    - buildah login -u $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - buildah build -t $FQ_IMAGE_NAME
    - buildah push $FQ_IMAGE_NAME
